{% set name = "ocrmypdf" %}
{% set version = "12.4.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ocrmypdf-{{ version }}.tar.gz
  sha256: 94c1bbc93a93493388930bbc6ede131ea3a17c30476033d99162647c0dc874f6

build:
  number: 0
  noarch: python
  entry_points:
    - ocrmypdf = ocrmypdf.__main__:run
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools_scm
    - setuptools_scm_git_archive
  run:
    - cffi >=1.9.1
    - coloredlogs >=14.0
    - img2pdf >=0.3.0,<0.5
    - pdfminer.six >=20191110,!=20200720,<=20201018
    - pikepdf
    - pillow >=7.0.0
    - pluggy >=0.13.0,<1.0
    - python >=3.6
    - reportlab >=3.3.0
    - sortedcontainers
    - tqdm >=4
    - ghostscript
    - img2pdf
    - leptonica
    - pngquant
    - qpdf
    - tesseract
    - unpaper

test:
  imports:
    - ocrmypdf
    - ocrmypdf._exec
  commands:
    - pip check
    - ocrmypdf --help
  requires:
    - pip

about:
  home: https://github.com/jbarlow83/OCRmyPDF
  summary: OCRmyPDF adds an OCR text layer to scanned PDF files, allowing them to be searched
  dev_url: https://github.com/jbarlow83/ocrmypdf
  license: MPL-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - izahn
