{% set name = "ocrmypdf" %}
{% set version = "14.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ocrmypdf-{{ version }}.tar.gz
  sha256: 19e29601a117ec7ea4d4ced6ad5e94f29f8a378d7d41862de31ef1de7e67f0f1

build:
  number: 0
  noarch: python
  entry_points:
    - ocrmypdf = ocrmypdf.__main__:run
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools_scm
    - setuptools_scm_git_archive
  run:
    - coloredlogs >=15
    - img2pdf >=0.4
    - packaging >=20
    - pdfminer.six >=20201018
    - pikepdf >=5.1
    - pillow >=8.3.2
    - pluggy >=0.13.0
    - python >=3.7
    - reportlab >=3.5
    - importlib_resources
    - importlib_metadata
    - tqdm >=4
    - ghostscript
    - img2pdf
    - pngquant
    - qpdf
    - tesseract
    - unpaper
    - packaging

test:
  imports:
    - ocrmypdf
    - ocrmypdf._exec
  commands:
    - pip check
    - ocrmypdf --help
  requires:
    - pip

about:
  home: https://github.com/jbarlow83/OCRmyPDF
  summary: OCRmyPDF adds an OCR text layer to scanned PDF files, allowing them to be searched
  dev_url: https://github.com/jbarlow83/ocrmypdf
  license: MPL-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - izahn
