# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: ocrmypdf
  version: "17.8.1"
  python_min: "3.11"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/ocrmypdf-${{ version }}.tar.gz
  sha256: 6f72e4da5fd7805e5d677c0fc55ad380c70e1c7ad33dd9ce2402575194803e08

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - ocrmypdf = ocrmypdf.__main__:run

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }},<4
    - deprecation >=2.1.0
    - fpdf2 >=2.8.0
    - img2pdf >=0.5
    - packaging >=20
    - pdfminer-six >=20260107
    - pillow-heif
    - pngquant
    - pikepdf >=10
    - pypdfium2 >=5.0.0
    - pillow >=10.0.1
    - pydantic >=2.12.5
    - pluggy >=1
    - rich >=13
    - tesseract
    - uharfbuzz >=0.53.2

tests:
  - python:
      imports:
        - ocrmypdf
        - ocrmypdf._exec
      pip_check: false
      python_version:
        - ${{ python_min }}.*
        - "*"
  - files:
      source:
        - tests/resources/linn.pdf
        - tests/resources/graph_ocred.pdf
    script:
      - ocrmypdf --help
      - ocrmypdf --version
      - ocrmypdf --mode force --output-type pdf tests/resources/linn.pdf /tmp/ocr_output.pdf
      - test -s /tmp/ocr_output.pdf
      - ocrmypdf --mode skip --optimize 3 --output-type pdf tests/resources/graph_ocred.pdf /tmp/opt_output.pdf
      - test -s /tmp/opt_output.pdf

about:
  summary: OCRmyPDF adds an OCR text layer to scanned PDF files, allowing them to be searched
  license: MPL-2.0
  license_file: LICENSE
  repository: https://github.com/ocrmypdf/OCRmyPDF
  homepage: https://github.com/jbarlow83/OCRmyPDF

extra:
  recipe-maintainers:
    - izahn
    - carlodri
    - rxm7706
